- README.md
BREAKING CHANGE:
Bumping to 1.0
> fix(Build): bump to 1.0

- README.md
- src/@terminus/ngx-tools/src/public-api.ts
- src/@terminus/ngx-tools/src/verify-types/is-array/is-array.spec.ts
- src/@terminus/ngx-tools/src/verify-types/is-array/is-array.ts
- src/@terminus/ngx-tools/src/verify-types/is-boolean/is-boolean.spec.ts
- src/@terminus/ngx-tools/src/verify-types/is-boolean/is-boolean.ts
- src/@terminus/ngx-tools/src/verify-types/is-function/is-function.spec.ts
- src/@terminus/ngx-tools/src/verify-types/is-function/is-function.ts
- src/@terminus/ngx-tools/src/verify-types/is-object/is-object.spec.ts
- src/@terminus/ngx-tools/src/verify-types/is-object/is-object.ts
- src/@terminus/ngx-tools/src/verify-types/is-string/is-string.spec.ts
- src/@terminus/ngx-tools/src/verify-types/is-string/is-string.ts
String, Object, Boolean, Array, Function
> feat(Utility): add functions to check for type

- README.md
- src/@terminus/ngx-tools/src/array-contains-object/array-contains-object.spec.ts
- src/@terminus/ngx-tools/src/array-contains-object/array-contains-object.ts
- src/@terminus/ngx-tools/src/public-api.ts
> feat: add utility to test if object is in array

- package.json
- scripts/inject-version.sh
- src/@terminus/ngx-tools/src/public-api.ts
- src/@terminus/ngx-tools/src/version/version.ts
- src/demo/app/home/home.component.ts
- yarn.lock
> fix(Build): expose library version number

- scripts/inject-version.sh
> fix(Build): test version injection

- README.md
> docs: add missing regex to readme, sort tables

- .all-contributorsrc
- README.md
> chore: update readme, add contributor

- config/setup-jest.ts
- package.json
- scripts/util/config.ts
- scripts/util/release_mgmt.ts
- src/@terminus/ngx-tools/src/document/document.service.spec.ts
- src/@terminus/ngx-tools/src/document/document.service.ts
- src/@terminus/ngx-tools/src/public-api.ts
- src/@terminus/ngx-tools/src/retry-with-backoff/retry-with-backoff.ts
- src/@terminus/ngx-tools/src/window/window.service.spec.ts
- src/@terminus/ngx-tools/src/window/window.service.ts
- src/@terminus/ngx-tools/testing/src/mocks/document.service.mock.ts
- src/@terminus/ngx-tools/testing/src/mocks/window.service.mock.ts
- src/@terminus/ngx-tools/testing/src/public-api.ts
- src/demo/app/app.component.spec.ts
- src/demo/app/app.component.ts
- src/demo/app/app.module.ts
- src/demo/app/home/home.component.html
- src/demo/app/home/home.component.spec.ts
- src/demo/app/home/home.component.ts
- src/demo/app/no-content/no-content.component.ts
- src/demo/custom-typings.d.ts
- src/demo/polyfills.browser.ts
- src/typings.d.ts
- yarn.lock
- create window service
- create document service
- expose mocks
closes #8
> 8 window document services

- README.md
- src/@terminus/ngx-tools/src/control-has-required-field/control-has-required-field.spec.ts
- src/@terminus/ngx-tools/src/control-has-required-field/control-has-required-field.ts
- src/@terminus/ngx-tools/src/form-group-has-required-field/form-group-has-required-field.spec.ts
- src/@terminus/ngx-tools/src/form-group-has-required-field/form-group-has-required-field.ts
> feat(Utility): add utilities to check for required form controls

- src/@terminus/ngx-tools/src/control-has-required-field/control-has-required-field.ts
- src/@terminus/ngx-tools/src/public-api.ts
Thou shalt not rush a release before a meeting.
> fix(Utility): export form utilities

- package.json
- src/@terminus/ngx-tools/testing/src/mocks/elementRef.mock.ts
> fix(Testing): elementRef now contains nativeElement object

- README.md
- package.json
> fix: fake fix to test release

- ngx-tools/package.json
- package.json
> fix: move publish config to lib pckage and move files after build

- README.md
- package.json
> fix: back to main package.json

- package.json
> fix: add repository to main package.json

- README.md
- ngx-tools/regex/public-api.ts
- ngx-tools/regex/src/letters/contains-lower.regex.spec.ts
- ngx-tools/regex/src/letters/contains-lower.regex.ts
- ngx-tools/regex/src/letters/contains-upper.regex.spec.ts
- ngx-tools/regex/src/letters/contains-upper.regex.ts
- ngx-tools/regex/src/letters/only-letters.regex.spec.ts
- ngx-tools/regex/src/letters/only-letters.regex.ts
- Add lowercase regex & regex creator
- Add uppercase regex & regex creator
- Rename letters.regex file for clarity
ISSUES CLOSED: #40, #41
> feat(Regex): lowercase and uppercase regex helpers

- README.md
- ngx-tools/regex/public-api.ts
- ngx-tools/regex/src/numbers/contains-numbers.regex.ts
- ngx-tools/regex/src/special-characters/special-characters.regex.spec.ts
- ngx-tools/regex/src/special-characters/special-characters.regex.ts
> feat(Regex): special characters regex and creator helper

- README.md
- ngx-tools/coercion/README.md
- ngx-tools/keycodes/README.md
- ngx-tools/regex/README.md
- ngx-tools/src/README.md
- ngx-tools/src/group-by/group-by.ts
- ngx-tools/src/has-required-control/has-required-control.ts
- ngx-tools/src/retry-with-backoff/delay-calculator.ts
- ngx-tools/src/retry-with-backoff/retry-with-backoff.ts
- ngx-tools/testing/README.md
- ngx-tools/testing/src/mocks/change-detector-ref.mock.ts
- ngx-tools/testing/src/utilities/dispatch-events.ts
- ngx-tools/testing/src/utilities/event-objects.ts
- ngx-tools/testing/src/utilities/type-in-element.ts
- package.json
- yarn.lock
- Add missing docs
- Add examples to JSDocs
- Split docs up for better clarity
- Add missing dependencies to allow StackBlitz to spin up the repo.
> 61 regex usage docs

- README.md
- package.json
> Hotfix deps

- README.md
> docs: removed outdated resource

- .gitignore
- ngx-tools/package.json
- ngx-tools/src/debounce/debounce.spec.ts
- ngx-tools/testing/src/mocks/document.service.mock.ts
- ngx-tools/testing/src/mocks/window.service.mock.ts
- package.json
- remove jasmine spies
- stop tracking coverage for mocks
> 76 remove jasmine spies

- karma.conf.js
- package.json
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/tsconfig.app.json
- src/tsconfig.packages.json
- src/tsconfig.spec.json
- tsconfig.json
- yarn.lock
> test(Build): demo app tests now run against local code

- ngx-tools/src/README.md
- ngx-tools/src/input-has-changed/input-has-changed.spec.ts
- ngx-tools/src/input-has-changed/input-has-changed.ts
> feat(Utility): helper function to determine if an Angular @Input has changed

- ngx-tools/package.json
- ngx-tools/src/README.md
- ngx-tools/src/get-store-value/get-store-value.spec.ts
- ngx-tools/src/get-store-value/get-store-value.ts
- ngx-tools/src/public-api.ts
- package.json
- yarn.lock
- `@ngrx/store` is now a peer dependency
ISSUES CLOSED: #88
> feat(Utility): helper to get the value of a store entry

- .github/CODEOWNERS
- CODE_OF_CONDUCT.md
> add missing docs

- ngx-tools/src/README.md
- ngx-tools/src/get-form-control-value/get-form-control-value.spec.ts
- ngx-tools/src/get-form-control-value/get-form-control-value.ts
- ngx-tools/src/public-api.ts
> feat(Utility): helper function to get the current value of a form control

- ngx-tools/src/README.md
- ngx-tools/src/compact-array/compact-array.spec.ts
- ngx-tools/src/compact-array/compact-array.ts
- ngx-tools/src/public-api.ts
> feat(Utility): create compactArray fn to remove null|undefined values from an array

- .circleci/config.yml
- .codecov.yml
- ngx-tools/jest.all.config.js
- ngx-tools/jest.coercion.config.js
- ngx-tools/jest.keycodes.config.js
- ngx-tools/jest.regex.config.js
- ngx-tools/jest.testing.config.js
- ngx-tools/jest.utilities.config.js
- package.json
> chore(CI): add codecov.yml to split test coverage by entry point

- ngx-tools/src/README.md
- ngx-tools/src/public-api.ts
- ngx-tools/src/to-camel-case/to-camel-case.spec.ts
- ngx-tools/src/to-camel-case/to-camel-case.ts
- package.json
> feat(Utility): helper function to convert a string to camelCase

- ngx-tools/testing/README.md
- ngx-tools/testing/public-api.ts
- ngx-tools/testing/src/utilities/configure-test-bed.ts
> feat(Testing): helper to create testbed instance with no white space

- renovate.json
> chore(CI): update renovate json for library structure

- ngx-tools/testing/README.md
- ngx-tools/testing/public-api.ts
- ngx-tools/testing/src/mocks/renderer.mock.ts
- add mock for renderer (1)
- update docs for both renderer mocks
ISSUES CLOSED: #112
> feat(Testing): add rendererMock, update docs for both renderer mocks

- ngx-tools/src/README.md
- ngx-tools/src/public-api.ts
- ngx-tools/src/update-control-on-input-changes/update-control-on-input-changes.spec.ts
- ngx-tools/src/update-control-on-input-changes/update-control-on-input-changes.ts
Helper to update a form control when an input changes.
> feat(Utility): Helper to update a form control when an input changes

- ngx-tools/src/README.md
- ngx-tools/src/public-api.ts
- ngx-tools/src/return-array-value-from-hash/return-array-value-from-hash.spec.ts
- ngx-tools/src/return-array-value-from-hash/return-array-value-from-hash.ts
Helper function to return an array of values from an hash object
> feat(Utility): Helper function to return an array of values from an hash object

- ngx-tools/package.json
- ngx-tools/src/README.md
- ngx-tools/src/merge/merge.spec.ts
- ngx-tools/src/merge/merge.ts
- ngx-tools/src/public-api.ts
- package.json
- yarn.lock
> feat(Utility): helper to deep merge JS objects

- ngx-tools/package.json
- package.json
> fix(Build): now publishing to @next tag

- ngx-tools/testing/src/mocks/renderer2.mock.ts
> fix(Testing): add void implementations to Renderer2 mock

- ngx-tools/src/README.md
- ngx-tools/src/public-api.ts
- ngx-tools/src/set-form-control-value/set-form-control-value.spec.ts
- ngx-tools/src/set-form-control-value/set-form-control-value.ts
Helper to set a form control value
> feat(Utility): Helper to set a form control value

- ngx-tools/testing/src/mocks/window.service.mock.ts
> fix(Testing): add a default value for location.protocol

- ngx-tools/testing/README.md
- ngx-tools/testing/src/utilities/get-child-component-instance-from-fixture.spec.ts
- ngx-tools/testing/src/utilities/get-child-component-instance-from-fixture.ts
> feat(Testing): add helper to return component instance from within testbed fixture

- ngx-tools/src/README.md
- ngx-tools/src/public-api.ts
- ngx-tools/src/round-number/round-number.spec.ts
- ngx-tools/src/round-number/round-number.ts
- ngx-tools/src/verify-types/index.ts
- ngx-tools/src/verify-types/is-number/is-number.spec.ts
- ngx-tools/src/verify-types/is-number/is-number.ts
> 147 round numbers

- ngx-tools/coercion/README.md
- ngx-tools/keycodes/README.md
- ngx-tools/regex/README.md
- ngx-tools/src/README.md
- ngx-tools/src/return-array-value-from-hash/return-array-value-from-hash.ts
- ngx-tools/testing/README.md
> docs(Docs): add links to source files

- ngx-tools/src/debounce/debounce.spec.ts
> test(Utility): add test to ensure debounce context is not lost

- ngx-tools/src/jwt-token-managment/testing-public-api.ts
- ngx-tools/src/jwt-token-managment/utilities/token-escalator.mock.ts
- ngx-tools/src/jwt-token-managment/utilities/token-escalator.ts
Adds a mock to make this more testable.
> chore(Utility): adding TokenEscalator mock for testing

- ngx-tools/testing/src/mocks/window.service.mock.ts
> feat(Testing): allow scrollTo to be mocked
